version: '3.1'

services:
  restaurantsdb:
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${RESTAURANTFINDER_DB_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${RESTAURANTFINDER_DB_ROOT_PASSWORD}
    volumes:
      - restaurantdb_volume:/data/db

  restaurantsdb_mongo_express:
    image: mongo-express:latest
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${RESTAURANTFINDER_DB_ROOT_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${RESTAURANTFINDER_DB_ROOT_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://${RESTAURANTFINDER_DB_ROOT_USER}:${RESTAURANTFINDER_DB_ROOT_PASSWORD}@restaurantsdb:27017/
    depends_on:
      - restaurantsdb

volumes:
  restaurantdb_volume:
    driver: local